[Redis]
#IpHost = "10.225.10.190:6379"
IpHost = "0.0.0.0:6379"
Db = 0
#连接池大小
PoolSize = 15
#最小连接数
MinIdleConns = 1
#连接检查频率
IdleCheckFrequency = 1

[FileServer]
Host = "10.225.137.167"
Port = "9999"
VideoPath = "cloud_test/video/dev"
LogPath = "cloud_test/log/dev"