// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/connect.proto

package Device

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PingResponseStatus int32

const (
	PingResponse_Wait    PingResponseStatus = 0 //等待
	PingResponse_Success PingResponseStatus = 1 //成功
	PingResponse_Fail    PingResponseStatus = 2 //失败
)

// Enum value maps for PingResponseStatus.
var (
	PingResponseStatus_name = map[int32]string{
		0: "Wait",
		1: "Success",
		2: "Fail",
	}
	PingResponseStatus_value = map[string]int32{
		"Wait":    0,
		"Success": 1,
		"Fail":    2,
	}
)

func (x PingResponseStatus) Enum() *PingResponseStatus {
	p := new(PingResponseStatus)
	*p = x
	return p
}

func (x PingResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PingResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_connect_proto_enumTypes[0].Descriptor()
}

func (PingResponseStatus) Type() protoreflect.EnumType {
	return &file_proto_connect_proto_enumTypes[0]
}

func (x PingResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PingResponseStatus.Descriptor instead.
func (PingResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{3, 0}
}

type ConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SerId string `protobuf:"bytes,1,opt,name=serId,proto3" json:"serId,omitempty"` //设备序列号
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetSerId() string {
	if x != nil {
		return x.SerId
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` //启动状态
	Port   string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`      //启动端口
	Code   string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`      //验证码
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ConnectResponse) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ConnectResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{2}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      PingResponseStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=Device.PingResponseStatus" json:"Status,omitempty"`
	VideoPort   string             `protobuf:"bytes,2,opt,name=VideoPort,proto3" json:"VideoPort,omitempty"`     //视频端口
	ControlPort string             `protobuf:"bytes,3,opt,name=ControlPort,proto3" json:"ControlPort,omitempty"` //控制端口
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetStatus() PingResponseStatus {
	if x != nil {
		return x.Status
	}
	return PingResponse_Wait
}

func (x *PingResponse) GetVideoPort() string {
	if x != nil {
		return x.VideoPort
	}
	return ""
}

func (x *PingResponse) GetControlPort() string {
	if x != nil {
		return x.ControlPort
	}
	return ""
}

type VideoStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VideoStreamRequest) Reset() {
	*x = VideoStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStreamRequest) ProtoMessage() {}

func (x *VideoStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStreamRequest.ProtoReflect.Descriptor instead.
func (*VideoStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{4}
}

type VideoStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PicBytes []byte `protobuf:"bytes,1,opt,name=PicBytes,proto3" json:"PicBytes,omitempty"` //图片数据
}

func (x *VideoStreamResponse) Reset() {
	*x = VideoStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStreamResponse) ProtoMessage() {}

func (x *VideoStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStreamResponse.ProtoReflect.Descriptor instead.
func (*VideoStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{5}
}

func (x *VideoStreamResponse) GetPicBytes() []byte {
	if x != nil {
		return x.PicBytes
	}
	return nil
}

type ControlStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` //操作指令
}

func (x *ControlStreamRequest) Reset() {
	*x = ControlStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStreamRequest) ProtoMessage() {}

func (x *ControlStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStreamRequest.ProtoReflect.Descriptor instead.
func (*ControlStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{6}
}

func (x *ControlStreamRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ControlStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` //执行结果
}

func (x *ControlStreamResponse) Reset() {
	*x = ControlStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStreamResponse) ProtoMessage() {}

func (x *ControlStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStreamResponse.ProtoReflect.Descriptor instead.
func (*ControlStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{7}
}

func (x *ControlStreamResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type InstallAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` //文件地址
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"` //设备id
}

func (x *InstallAppRequest) Reset() {
	*x = InstallAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppRequest) ProtoMessage() {}

func (x *InstallAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppRequest.ProtoReflect.Descriptor instead.
func (*InstallAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{8}
}

func (x *InstallAppRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *InstallAppRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type PushFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`   //文件地址
	Uid  string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`   //设备id
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` //文件名字
}

func (x *PushFileRequest) Reset() {
	*x = PushFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileRequest) ProtoMessage() {}

func (x *PushFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileRequest.ProtoReflect.Descriptor instead.
func (*PushFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{9}
}

func (x *PushFileRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PushFileRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PushFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PushFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` //结果
}

func (x *PushFileResponse) Reset() {
	*x = PushFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileResponse) ProtoMessage() {}

func (x *PushFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileResponse.ProtoReflect.Descriptor instead.
func (*PushFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{10}
}

func (x *PushFileResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type InstallAppStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` //安装查询的id
}

func (x *InstallAppStreamResponse) Reset() {
	*x = InstallAppStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallAppStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppStreamResponse) ProtoMessage() {}

func (x *InstallAppStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppStreamResponse.ProtoReflect.Descriptor instead.
func (*InstallAppStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{11}
}

func (x *InstallAppStreamResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type LogStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`   //标志开始结束
	LogId   int32 `protobuf:"varint,2,opt,name=logId,proto3" json:"logId,omitempty"`     //云测logId
	UserId  int32 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`   //用户id
	GroupId int32 `protobuf:"varint,4,opt,name=groupId,proto3" json:"groupId,omitempty"` //组id
}

func (x *LogStreamRequest) Reset() {
	*x = LogStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamRequest) ProtoMessage() {}

func (x *LogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamRequest.ProtoReflect.Descriptor instead.
func (*LogStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{12}
}

func (x *LogStreamRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *LogStreamRequest) GetLogId() int32 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *LogStreamRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LogStreamRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type LogStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` //log数据
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{13}
}

func (x *LogStreamResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SaveVideoClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`   //标志开始结束
	LogId   int32  `protobuf:"varint,2,opt,name=logId,proto3" json:"logId,omitempty"`     //云测logId
	Port    int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`       //视频端口
	Uid     string `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`          //设备id
	UserId  int32  `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`   //用户id
	GroupId int32  `protobuf:"varint,6,opt,name=groupId,proto3" json:"groupId,omitempty"` //组id
}

func (x *SaveVideoClientRequest) Reset() {
	*x = SaveVideoClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveVideoClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVideoClientRequest) ProtoMessage() {}

func (x *SaveVideoClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVideoClientRequest.ProtoReflect.Descriptor instead.
func (*SaveVideoClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{14}
}

func (x *SaveVideoClientRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *SaveVideoClientRequest) GetLogId() int32 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *SaveVideoClientRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SaveVideoClientRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *SaveVideoClientRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SaveVideoClientRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type SaveVideoClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SaveVideoClientResponse) Reset() {
	*x = SaveVideoClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveVideoClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVideoClientResponse) ProtoMessage() {}

func (x *SaveVideoClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVideoClientResponse.ProtoReflect.Descriptor instead.
func (*SaveVideoClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{15}
}

func (x *SaveVideoClientResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RemoteDebugRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` //开关
}

func (x *RemoteDebugRequest) Reset() {
	*x = RemoteDebugRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteDebugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteDebugRequest) ProtoMessage() {}

func (x *RemoteDebugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteDebugRequest.ProtoReflect.Descriptor instead.
func (*RemoteDebugRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{16}
}

func (x *RemoteDebugRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type RemoteDebugResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"` //远程host
	Port string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"` //远程端口
}

func (x *RemoteDebugResponse) Reset() {
	*x = RemoteDebugResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteDebugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteDebugResponse) ProtoMessage() {}

func (x *RemoteDebugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteDebugResponse.ProtoReflect.Descriptor instead.
func (*RemoteDebugResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{17}
}

func (x *RemoteDebugResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RemoteDebugResponse) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type ResetEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResetEnvRequest) Reset() {
	*x = ResetEnvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetEnvRequest) ProtoMessage() {}

func (x *ResetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetEnvRequest.ProtoReflect.Descriptor instead.
func (*ResetEnvRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{18}
}

type ResetEnvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` //重置状态
}

func (x *ResetEnvResponse) Reset() {
	*x = ResetEnvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetEnvResponse) ProtoMessage() {}

func (x *ResetEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetEnvResponse.ProtoReflect.Descriptor instead.
func (*ResetEnvResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{19}
}

func (x *ResetEnvResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type VerifyCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` //签发的code
}

func (x *VerifyCodeRequest) Reset() {
	*x = VerifyCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeRequest) ProtoMessage() {}

func (x *VerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{20}
}

func (x *VerifyCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifyCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` //验证状态
}

func (x *VerifyCodeResponse) Reset() {
	*x = VerifyCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeResponse) ProtoMessage() {}

func (x *VerifyCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{21}
}

func (x *VerifyCodeResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type StopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` //签发的code
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{22}
}

func (x *StopRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{23}
}

type ShellStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` //shell指令
}

func (x *ShellStreamRequest) Reset() {
	*x = ShellStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStreamRequest) ProtoMessage() {}

func (x *ShellStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStreamRequest.ProtoReflect.Descriptor instead.
func (*ShellStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{24}
}

func (x *ShellStreamRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ShellStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` //结果
}

func (x *ShellStreamResponse) Reset() {
	*x = ShellStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connect_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStreamResponse) ProtoMessage() {}

func (x *ShellStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStreamResponse.ProtoReflect.Descriptor instead.
func (*ShellStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{25}
}

func (x *ShellStreamResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_connect_proto protoreflect.FileDescriptor

var file_proto_connect_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0x26, 0x0a,
	0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xae, 0x01, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x29, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x61, 0x69, 0x74, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x46, 0x61, 0x69, 0x6c, 0x10, 0x02, 0x22, 0x14, 0x0a, 0x12, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x31,
	0x0a, 0x13, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x69, 0x63, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x50, 0x69, 0x63, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x37, 0x0a, 0x11, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x49, 0x0a,
	0x0f, 0x50, 0x75, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x10, 0x50, 0x75, 0x73, 0x68,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x32, 0x0a, 0x18, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x41,
	0x70, 0x70, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x72, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x11,
	0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x9e, 0x01, 0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x17, 0x53, 0x61, 0x76, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x2c, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x62,
	0x75, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x3d, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x62, 0x75, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x27, 0x0a, 0x11, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2c, 0x0a, 0x12, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x21, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x74, 0x6f,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x53, 0x68, 0x65,
	0x6c, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x53, 0x68, 0x65,
	0x6c, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x9d, 0x01, 0x0a, 0x0d, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x16, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x53, 0x61, 0x76, 0x65,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1e, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x96, 0x06, 0x0a, 0x12, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x33, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x13, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x1a, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x52, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x1c, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x12, 0x4d, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x41,
	0x70, 0x70, 0x12, 0x19, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x41, 0x70,
	0x70, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x46, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x18, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x48, 0x0a, 0x0b, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x62, 0x75, 0x67, 0x12, 0x1a, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x62, 0x75, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x62, 0x75, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x65, 0x74, 0x45, 0x6e,
	0x76, 0x12, 0x17, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a,
	0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x13, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x1a, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x3f, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50,
	0x75, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_connect_proto_rawDescOnce sync.Once
	file_proto_connect_proto_rawDescData = file_proto_connect_proto_rawDesc
)

func file_proto_connect_proto_rawDescGZIP() []byte {
	file_proto_connect_proto_rawDescOnce.Do(func() {
		file_proto_connect_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_connect_proto_rawDescData)
	})
	return file_proto_connect_proto_rawDescData
}

var file_proto_connect_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_connect_proto_goTypes = []interface{}{
	(PingResponseStatus)(0),          // 0: Device.PingResponse.status
	(*ConnectRequest)(nil),           // 1: Device.ConnectRequest
	(*ConnectResponse)(nil),          // 2: Device.ConnectResponse
	(*PingRequest)(nil),              // 3: Device.PingRequest
	(*PingResponse)(nil),             // 4: Device.PingResponse
	(*VideoStreamRequest)(nil),       // 5: Device.VideoStreamRequest
	(*VideoStreamResponse)(nil),      // 6: Device.VideoStreamResponse
	(*ControlStreamRequest)(nil),     // 7: Device.ControlStreamRequest
	(*ControlStreamResponse)(nil),    // 8: Device.ControlStreamResponse
	(*InstallAppRequest)(nil),        // 9: Device.InstallAppRequest
	(*PushFileRequest)(nil),          // 10: Device.PushFileRequest
	(*PushFileResponse)(nil),         // 11: Device.PushFileResponse
	(*InstallAppStreamResponse)(nil), // 12: Device.InstallAppStreamResponse
	(*LogStreamRequest)(nil),         // 13: Device.LogStreamRequest
	(*LogStreamResponse)(nil),        // 14: Device.LogStreamResponse
	(*SaveVideoClientRequest)(nil),   // 15: Device.SaveVideoClientRequest
	(*SaveVideoClientResponse)(nil),  // 16: Device.SaveVideoClientResponse
	(*RemoteDebugRequest)(nil),       // 17: Device.RemoteDebugRequest
	(*RemoteDebugResponse)(nil),      // 18: Device.RemoteDebugResponse
	(*ResetEnvRequest)(nil),          // 19: Device.ResetEnvRequest
	(*ResetEnvResponse)(nil),         // 20: Device.ResetEnvResponse
	(*VerifyCodeRequest)(nil),        // 21: Device.VerifyCodeRequest
	(*VerifyCodeResponse)(nil),       // 22: Device.VerifyCodeResponse
	(*StopRequest)(nil),              // 23: Device.StopRequest
	(*StopResponse)(nil),             // 24: Device.StopResponse
	(*ShellStreamRequest)(nil),       // 25: Device.ShellStreamRequest
	(*ShellStreamResponse)(nil),      // 26: Device.ShellStreamResponse
}
var file_proto_connect_proto_depIdxs = []int32{
	0,  // 0: Device.PingResponse.Status:type_name -> Device.PingResponse.status
	1,  // 1: Device.DeviceService.Connect:input_type -> Device.ConnectRequest
	15, // 2: Device.DeviceService.SaveVideo:input_type -> Device.SaveVideoClientRequest
	3,  // 3: Device.DeviceAgentService.Ping:input_type -> Device.PingRequest
	5,  // 4: Device.DeviceAgentService.VideoStream:input_type -> Device.VideoStreamRequest
	7,  // 5: Device.DeviceAgentService.ControlStream:input_type -> Device.ControlStreamRequest
	9,  // 6: Device.DeviceAgentService.InstallApp:input_type -> Device.InstallAppRequest
	13, // 7: Device.DeviceAgentService.LogStream:input_type -> Device.LogStreamRequest
	17, // 8: Device.DeviceAgentService.RemoteDebug:input_type -> Device.RemoteDebugRequest
	19, // 9: Device.DeviceAgentService.ResetEnv:input_type -> Device.ResetEnvRequest
	21, // 10: Device.DeviceAgentService.VerifyCode:input_type -> Device.VerifyCodeRequest
	23, // 11: Device.DeviceAgentService.Stop:input_type -> Device.StopRequest
	25, // 12: Device.DeviceAgentService.ShellStream:input_type -> Device.ShellStreamRequest
	10, // 13: Device.DeviceAgentService.PushFile:input_type -> Device.PushFileRequest
	2,  // 14: Device.DeviceService.Connect:output_type -> Device.ConnectResponse
	16, // 15: Device.DeviceService.SaveVideo:output_type -> Device.SaveVideoClientResponse
	4,  // 16: Device.DeviceAgentService.Ping:output_type -> Device.PingResponse
	6,  // 17: Device.DeviceAgentService.VideoStream:output_type -> Device.VideoStreamResponse
	8,  // 18: Device.DeviceAgentService.ControlStream:output_type -> Device.ControlStreamResponse
	12, // 19: Device.DeviceAgentService.InstallApp:output_type -> Device.InstallAppStreamResponse
	14, // 20: Device.DeviceAgentService.LogStream:output_type -> Device.LogStreamResponse
	18, // 21: Device.DeviceAgentService.RemoteDebug:output_type -> Device.RemoteDebugResponse
	20, // 22: Device.DeviceAgentService.ResetEnv:output_type -> Device.ResetEnvResponse
	22, // 23: Device.DeviceAgentService.VerifyCode:output_type -> Device.VerifyCodeResponse
	24, // 24: Device.DeviceAgentService.Stop:output_type -> Device.StopResponse
	26, // 25: Device.DeviceAgentService.ShellStream:output_type -> Device.ShellStreamResponse
	11, // 26: Device.DeviceAgentService.PushFile:output_type -> Device.PushFileResponse
	14, // [14:27] is the sub-list for method output_type
	1,  // [1:14] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_connect_proto_init() }
func file_proto_connect_proto_init() {
	if File_proto_connect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_connect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallAppStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveVideoClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveVideoClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteDebugRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteDebugResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetEnvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetEnvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connect_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_connect_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_connect_proto_goTypes,
		DependencyIndexes: file_proto_connect_proto_depIdxs,
		EnumInfos:         file_proto_connect_proto_enumTypes,
		MessageInfos:      file_proto_connect_proto_msgTypes,
	}.Build()
	File_proto_connect_proto = out.File
	file_proto_connect_proto_rawDesc = nil
	file_proto_connect_proto_goTypes = nil
	file_proto_connect_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceServiceClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	SaveVideo(ctx context.Context, in *SaveVideoClientRequest, opts ...grpc.CallOption) (*SaveVideoClientResponse, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/Device.DeviceService/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) SaveVideo(ctx context.Context, in *SaveVideoClientRequest, opts ...grpc.CallOption) (*SaveVideoClientResponse, error) {
	out := new(SaveVideoClientResponse)
	err := c.cc.Invoke(ctx, "/Device.DeviceService/SaveVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
type DeviceServiceServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	SaveVideo(context.Context, *SaveVideoClientRequest) (*SaveVideoClientResponse, error)
}

// UnimplementedDeviceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceServiceServer struct {
}

func (*UnimplementedDeviceServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (*UnimplementedDeviceServiceServer) SaveVideo(context.Context, *SaveVideoClientRequest) (*SaveVideoClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveVideo not implemented")
}

func RegisterDeviceServiceServer(s *grpc.Server, srv DeviceServiceServer) {
	s.RegisterService(&_DeviceService_serviceDesc, srv)
}

func _DeviceService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device.DeviceService/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_SaveVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveVideoClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).SaveVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device.DeviceService/SaveVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).SaveVideo(ctx, req.(*SaveVideoClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Device.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _DeviceService_Connect_Handler,
		},
		{
			MethodName: "SaveVideo",
			Handler:    _DeviceService_SaveVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/connect.proto",
}

// DeviceAgentServiceClient is the client API for DeviceAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceAgentServiceClient interface {
	//测试是否启动成功
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	//视频流
	VideoStream(ctx context.Context, in *VideoStreamRequest, opts ...grpc.CallOption) (DeviceAgentService_VideoStreamClient, error)
	//控制
	ControlStream(ctx context.Context, opts ...grpc.CallOption) (DeviceAgentService_ControlStreamClient, error)
	//安装应用
	InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (DeviceAgentService_InstallAppClient, error)
	//log流
	LogStream(ctx context.Context, opts ...grpc.CallOption) (DeviceAgentService_LogStreamClient, error)
	//远程调试
	RemoteDebug(ctx context.Context, in *RemoteDebugRequest, opts ...grpc.CallOption) (*RemoteDebugResponse, error)
	ResetEnv(ctx context.Context, in *ResetEnvRequest, opts ...grpc.CallOption) (*ResetEnvResponse, error)
	VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*VerifyCodeResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	ShellStream(ctx context.Context, opts ...grpc.CallOption) (DeviceAgentService_ShellStreamClient, error)
	PushFile(ctx context.Context, in *PushFileRequest, opts ...grpc.CallOption) (*PushFileResponse, error)
}

type deviceAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceAgentServiceClient(cc grpc.ClientConnInterface) DeviceAgentServiceClient {
	return &deviceAgentServiceClient{cc}
}

func (c *deviceAgentServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/Device.DeviceAgentService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentServiceClient) VideoStream(ctx context.Context, in *VideoStreamRequest, opts ...grpc.CallOption) (DeviceAgentService_VideoStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeviceAgentService_serviceDesc.Streams[0], "/Device.DeviceAgentService/VideoStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceAgentServiceVideoStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeviceAgentService_VideoStreamClient interface {
	Recv() (*VideoStreamResponse, error)
	grpc.ClientStream
}

type deviceAgentServiceVideoStreamClient struct {
	grpc.ClientStream
}

func (x *deviceAgentServiceVideoStreamClient) Recv() (*VideoStreamResponse, error) {
	m := new(VideoStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deviceAgentServiceClient) ControlStream(ctx context.Context, opts ...grpc.CallOption) (DeviceAgentService_ControlStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeviceAgentService_serviceDesc.Streams[1], "/Device.DeviceAgentService/ControlStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceAgentServiceControlStreamClient{stream}
	return x, nil
}

type DeviceAgentService_ControlStreamClient interface {
	Send(*ControlStreamRequest) error
	Recv() (*ControlStreamResponse, error)
	grpc.ClientStream
}

type deviceAgentServiceControlStreamClient struct {
	grpc.ClientStream
}

func (x *deviceAgentServiceControlStreamClient) Send(m *ControlStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *deviceAgentServiceControlStreamClient) Recv() (*ControlStreamResponse, error) {
	m := new(ControlStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deviceAgentServiceClient) InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (DeviceAgentService_InstallAppClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeviceAgentService_serviceDesc.Streams[2], "/Device.DeviceAgentService/InstallApp", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceAgentServiceInstallAppClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeviceAgentService_InstallAppClient interface {
	Recv() (*InstallAppStreamResponse, error)
	grpc.ClientStream
}

type deviceAgentServiceInstallAppClient struct {
	grpc.ClientStream
}

func (x *deviceAgentServiceInstallAppClient) Recv() (*InstallAppStreamResponse, error) {
	m := new(InstallAppStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deviceAgentServiceClient) LogStream(ctx context.Context, opts ...grpc.CallOption) (DeviceAgentService_LogStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeviceAgentService_serviceDesc.Streams[3], "/Device.DeviceAgentService/LogStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceAgentServiceLogStreamClient{stream}
	return x, nil
}

type DeviceAgentService_LogStreamClient interface {
	Send(*LogStreamRequest) error
	Recv() (*LogStreamResponse, error)
	grpc.ClientStream
}

type deviceAgentServiceLogStreamClient struct {
	grpc.ClientStream
}

func (x *deviceAgentServiceLogStreamClient) Send(m *LogStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *deviceAgentServiceLogStreamClient) Recv() (*LogStreamResponse, error) {
	m := new(LogStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deviceAgentServiceClient) RemoteDebug(ctx context.Context, in *RemoteDebugRequest, opts ...grpc.CallOption) (*RemoteDebugResponse, error) {
	out := new(RemoteDebugResponse)
	err := c.cc.Invoke(ctx, "/Device.DeviceAgentService/RemoteDebug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentServiceClient) ResetEnv(ctx context.Context, in *ResetEnvRequest, opts ...grpc.CallOption) (*ResetEnvResponse, error) {
	out := new(ResetEnvResponse)
	err := c.cc.Invoke(ctx, "/Device.DeviceAgentService/ResetEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentServiceClient) VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*VerifyCodeResponse, error) {
	out := new(VerifyCodeResponse)
	err := c.cc.Invoke(ctx, "/Device.DeviceAgentService/VerifyCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, "/Device.DeviceAgentService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentServiceClient) ShellStream(ctx context.Context, opts ...grpc.CallOption) (DeviceAgentService_ShellStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeviceAgentService_serviceDesc.Streams[4], "/Device.DeviceAgentService/ShellStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceAgentServiceShellStreamClient{stream}
	return x, nil
}

type DeviceAgentService_ShellStreamClient interface {
	Send(*ShellStreamRequest) error
	Recv() (*ShellStreamResponse, error)
	grpc.ClientStream
}

type deviceAgentServiceShellStreamClient struct {
	grpc.ClientStream
}

func (x *deviceAgentServiceShellStreamClient) Send(m *ShellStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *deviceAgentServiceShellStreamClient) Recv() (*ShellStreamResponse, error) {
	m := new(ShellStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deviceAgentServiceClient) PushFile(ctx context.Context, in *PushFileRequest, opts ...grpc.CallOption) (*PushFileResponse, error) {
	out := new(PushFileResponse)
	err := c.cc.Invoke(ctx, "/Device.DeviceAgentService/PushFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceAgentServiceServer is the server API for DeviceAgentService service.
type DeviceAgentServiceServer interface {
	//测试是否启动成功
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	//视频流
	VideoStream(*VideoStreamRequest, DeviceAgentService_VideoStreamServer) error
	//控制
	ControlStream(DeviceAgentService_ControlStreamServer) error
	//安装应用
	InstallApp(*InstallAppRequest, DeviceAgentService_InstallAppServer) error
	//log流
	LogStream(DeviceAgentService_LogStreamServer) error
	//远程调试
	RemoteDebug(context.Context, *RemoteDebugRequest) (*RemoteDebugResponse, error)
	ResetEnv(context.Context, *ResetEnvRequest) (*ResetEnvResponse, error)
	VerifyCode(context.Context, *VerifyCodeRequest) (*VerifyCodeResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	ShellStream(DeviceAgentService_ShellStreamServer) error
	PushFile(context.Context, *PushFileRequest) (*PushFileResponse, error)
}

// UnimplementedDeviceAgentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceAgentServiceServer struct {
}

func (*UnimplementedDeviceAgentServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedDeviceAgentServiceServer) VideoStream(*VideoStreamRequest, DeviceAgentService_VideoStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method VideoStream not implemented")
}
func (*UnimplementedDeviceAgentServiceServer) ControlStream(DeviceAgentService_ControlStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ControlStream not implemented")
}
func (*UnimplementedDeviceAgentServiceServer) InstallApp(*InstallAppRequest, DeviceAgentService_InstallAppServer) error {
	return status.Errorf(codes.Unimplemented, "method InstallApp not implemented")
}
func (*UnimplementedDeviceAgentServiceServer) LogStream(DeviceAgentService_LogStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method LogStream not implemented")
}
func (*UnimplementedDeviceAgentServiceServer) RemoteDebug(context.Context, *RemoteDebugRequest) (*RemoteDebugResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoteDebug not implemented")
}
func (*UnimplementedDeviceAgentServiceServer) ResetEnv(context.Context, *ResetEnvRequest) (*ResetEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetEnv not implemented")
}
func (*UnimplementedDeviceAgentServiceServer) VerifyCode(context.Context, *VerifyCodeRequest) (*VerifyCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCode not implemented")
}
func (*UnimplementedDeviceAgentServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedDeviceAgentServiceServer) ShellStream(DeviceAgentService_ShellStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ShellStream not implemented")
}
func (*UnimplementedDeviceAgentServiceServer) PushFile(context.Context, *PushFileRequest) (*PushFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushFile not implemented")
}

func RegisterDeviceAgentServiceServer(s *grpc.Server, srv DeviceAgentServiceServer) {
	s.RegisterService(&_DeviceAgentService_serviceDesc, srv)
}

func _DeviceAgentService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device.DeviceAgentService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgentService_VideoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VideoStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceAgentServiceServer).VideoStream(m, &deviceAgentServiceVideoStreamServer{stream})
}

type DeviceAgentService_VideoStreamServer interface {
	Send(*VideoStreamResponse) error
	grpc.ServerStream
}

type deviceAgentServiceVideoStreamServer struct {
	grpc.ServerStream
}

func (x *deviceAgentServiceVideoStreamServer) Send(m *VideoStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DeviceAgentService_ControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeviceAgentServiceServer).ControlStream(&deviceAgentServiceControlStreamServer{stream})
}

type DeviceAgentService_ControlStreamServer interface {
	Send(*ControlStreamResponse) error
	Recv() (*ControlStreamRequest, error)
	grpc.ServerStream
}

type deviceAgentServiceControlStreamServer struct {
	grpc.ServerStream
}

func (x *deviceAgentServiceControlStreamServer) Send(m *ControlStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *deviceAgentServiceControlStreamServer) Recv() (*ControlStreamRequest, error) {
	m := new(ControlStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DeviceAgentService_InstallApp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstallAppRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceAgentServiceServer).InstallApp(m, &deviceAgentServiceInstallAppServer{stream})
}

type DeviceAgentService_InstallAppServer interface {
	Send(*InstallAppStreamResponse) error
	grpc.ServerStream
}

type deviceAgentServiceInstallAppServer struct {
	grpc.ServerStream
}

func (x *deviceAgentServiceInstallAppServer) Send(m *InstallAppStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DeviceAgentService_LogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeviceAgentServiceServer).LogStream(&deviceAgentServiceLogStreamServer{stream})
}

type DeviceAgentService_LogStreamServer interface {
	Send(*LogStreamResponse) error
	Recv() (*LogStreamRequest, error)
	grpc.ServerStream
}

type deviceAgentServiceLogStreamServer struct {
	grpc.ServerStream
}

func (x *deviceAgentServiceLogStreamServer) Send(m *LogStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *deviceAgentServiceLogStreamServer) Recv() (*LogStreamRequest, error) {
	m := new(LogStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DeviceAgentService_RemoteDebug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteDebugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServiceServer).RemoteDebug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device.DeviceAgentService/RemoteDebug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServiceServer).RemoteDebug(ctx, req.(*RemoteDebugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgentService_ResetEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServiceServer).ResetEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device.DeviceAgentService/ResetEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServiceServer).ResetEnv(ctx, req.(*ResetEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgentService_VerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServiceServer).VerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device.DeviceAgentService/VerifyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServiceServer).VerifyCode(ctx, req.(*VerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgentService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device.DeviceAgentService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgentService_ShellStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeviceAgentServiceServer).ShellStream(&deviceAgentServiceShellStreamServer{stream})
}

type DeviceAgentService_ShellStreamServer interface {
	Send(*ShellStreamResponse) error
	Recv() (*ShellStreamRequest, error)
	grpc.ServerStream
}

type deviceAgentServiceShellStreamServer struct {
	grpc.ServerStream
}

func (x *deviceAgentServiceShellStreamServer) Send(m *ShellStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *deviceAgentServiceShellStreamServer) Recv() (*ShellStreamRequest, error) {
	m := new(ShellStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DeviceAgentService_PushFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServiceServer).PushFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device.DeviceAgentService/PushFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServiceServer).PushFile(ctx, req.(*PushFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceAgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Device.DeviceAgentService",
	HandlerType: (*DeviceAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DeviceAgentService_Ping_Handler,
		},
		{
			MethodName: "RemoteDebug",
			Handler:    _DeviceAgentService_RemoteDebug_Handler,
		},
		{
			MethodName: "ResetEnv",
			Handler:    _DeviceAgentService_ResetEnv_Handler,
		},
		{
			MethodName: "VerifyCode",
			Handler:    _DeviceAgentService_VerifyCode_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _DeviceAgentService_Stop_Handler,
		},
		{
			MethodName: "PushFile",
			Handler:    _DeviceAgentService_PushFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VideoStream",
			Handler:       _DeviceAgentService_VideoStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ControlStream",
			Handler:       _DeviceAgentService_ControlStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "InstallApp",
			Handler:       _DeviceAgentService_InstallApp_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LogStream",
			Handler:       _DeviceAgentService_LogStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ShellStream",
			Handler:       _DeviceAgentService_ShellStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/connect.proto",
}
